"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import django_env_overrides
import yaml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1)%$un3uey$ataudk-_(a&k*3=h(m=ns89#jmz1d&-m9vueyvf'

# Read config.yaml config file if it exists
if os.path.exists(os.path.join(BASE_DIR, 'config.yaml')):
    with open(os.path.join(BASE_DIR, 'config.yaml'), 'r') as stream:
        config = yaml.safe_load(stream)
else:
    config = {
        'LOG_FILE': 'logs/server.log',
        'LOG_LEVEL': 'INFO',

        'DEBUG': True,

        'FQDN': '*',
        'ALLOWED_HOSTS': ['*'],

        'FORCE_SCRIPT_NAME': '',
        'TEMPLATE_DIRS': ['build', 'templates', ],
        'DATA_MOUNT_DIR': str(BASE_DIR),

        'STATIC_FILES': ['static', 'build', 'build/static', 'build/assets', ],
        'STATIC_URL': '/static/',
        'MEDIA_URL': '/data/',

        'LANGUAGE_CODE': 'en-us',
        'USE_I18N': True,
        'USE_TZ': True,
        'TIME_ZONE': 'Asia/Kolkata',  # UTC

        'DATABASE': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(Path(BASE_DIR, 'data', 'db.sqlite3')),
        },
    }

LOG_FILE = config['LOG_FILE'] if 'LOG_FILE' in config else 'logs/server.log'
os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
LOG_LEVEL = config['LOG_LEVEL'] if 'LOG_LEVEL' in config else 'INFO'

APP_LOGGER = {
    "handlers": ["console", "file"],
    "level": LOG_LEVEL,
    "propagate": True,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "filename": LOG_FILE,
            "formatter": "verbose",
        },
    },

    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {process:d} {thread:d} [{name}:{lineno}]: {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },

        # Add Server Logger
        "server": APP_LOGGER,

        #Add App loggers "<app_name>": APP_LOGGER,        
        "core": APP_LOGGER,
        
    }
}

print("Config used is:", str(config))

DATA_MOUNT_DIR = config['DATA_MOUNT_DIR'] if 'DATA_MOUNT_DIR' in config else str(BASE_DIR)
DATA_DIR = str(Path(str(DATA_MOUNT_DIR), "data"))
os.makedirs(DATA_DIR, exist_ok=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config['DEBUG'] if 'DEBUG' in config else True

FQDN = config['FQDN'] if 'FQDN' in config else '*'

ALLOWED_HOSTS = config['ALLOWED_HOSTS'] if 'ALLOWED_HOSTS' in config else ['*']

X_FRAME_OPTIONS = 'SAMEORIGIN'
# APPEND_SLASH = False

# Disapbe COOP on insecure origins
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Trust local development environment
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'https://localhost',
    'http://127.0.0.1',
    'https://127.0.0.1',
]

USE_X_FORWARDED_HOST = True
FORCE_SCRIPT_NAME = config['FORCE_SCRIPT_NAME'] if 'FORCE_SCRIPT_NAME' in config else ''


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_ace',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

      # 'django_group_model',
    'django_crontab',
    'django_extensions',

    'rest_framework',  # Added for Django Rest Framework
    'rest_framework.authtoken',

    'drf_spectacular',

    'drf_yasg',
    # 'rest_framework_swagger',

    'django_filters',  # Added for filtering

    'corsheaders',

    'import_export',  # Import export

    # 'advanced_filters',  # Advanced filters

    # 'guardian',

    'massadmin',

    # 'revproxy', # Reverse proxy config

    'dbbackup',  # django-dbbackup

    # Project-Apps modules    
    'core',
    'product',
    'program',

    # Keeping django cleanup at the end
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middlewares.StripInsecureCoopMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, template_dir) for template_dir in
                 config['TEMPLATE_DIRS']] if 'TEMPLATE_DIRS' in config else
                [os.path.join(BASE_DIR, 'build'), os.path.join(BASE_DIR, 'templates'), ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.contextprocessors.site_configuration',
            ],
            # For swagger
            'libraries': {
                'staticfiles': 'django.templatetags.static',
            },
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': config['DATABASE'] if 'DATABASE' in config else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(Path(DATA_DIR, 'db.sqlite3')),
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = config['LANGUAGE_CODE'] if 'LANGUAGE_CODE' in config else 'en-us'

TIME_ZONE = config['TIME_ZONE'] if 'TIME_ZONE' in config else 'Asia/Kolkata'  # UTC

USE_I18N = config['USE_I18N'] if 'USE_I18N' in config else True

USE_TZ = config['USE_TZ'] if 'USE_TZ' in config else True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_SUFFIX = config['STATIC_URL'] if 'STATIC_URL' in config else '/static/'
STATIC_URL = FORCE_SCRIPT_NAME + STATIC_SUFFIX
MEDIA_SUFFIX = '/data/'
MEDIA_URL = config['MEDIA_URL'] if 'MEDIA_URL' in config else FORCE_SCRIPT_NAME + MEDIA_SUFFIX

# FILE_UPLOAD_HANDLERS=(
#     'django.core.files.uploadhandler.MemoryFileUploadHandler',
#     'django.core.files.uploadhandler.TemporaryFileUploadHandler',
# )

FILE_UPLOAD_MAX_MEMORY_SIZE = config[
    'FILE_UPLOAD_MAX_MEMORY_SIZE'] if 'FILE_UPLOAD_MAX_MEMORY_SIZE' in config else 1024 * 1024 * 10  # 10 MB
FILE_UPLOAD_TEMP_DIR = config['FILE_UPLOAD_TEMP_DIR'] if 'FILE_UPLOAD_TEMP_DIR' in config else str(
    Path(DATA_DIR, '_temp'))
SESSION_FILE_PATH = config['SESSION_FILE_PATH'] if 'SESSION_FILE_PATH' in config else str(
    Path(DATA_DIR, '_session'))
FILE_UPLOAD_DIRECTORY_PERMISSIONS = config[
    'FILE_UPLOAD_DIRECTORY_PERMISSIONS'] if 'FILE_UPLOAD_DIRECTORY_PERMISSIONS' in config else 0o644
FILE_UPLOAD_PERMISSIONS = config['FILE_UPLOAD_PERMISSIONS'] if 'FILE_UPLOAD_PERMISSIONS' in config else 0o644

# Create temp directories
os.makedirs(str(FILE_UPLOAD_TEMP_DIR), exist_ok=True)
os.makedirs(str(SESSION_FILE_PATH), exist_ok=True)

static_file_dir_config = config['STATIC_FILES'] if 'STATIC_FILES' in config else ['static', 'build', 'build/static',
                                                                                  'build/assets', ]

static_file_dirs=[str(Path(BASE_DIR, static_file_dir)) for static_file_dir in static_file_dir_config]

STATICFILES_DIRS = [static_file_dir for static_file_dir in static_file_dirs if os.path.exists(static_file_dir)]


# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_BASE_NAME = 'data'
MEDIA_ROOT = str(Path(str(DATA_MOUNT_DIR), MEDIA_BASE_NAME))
# os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend', # this is default
#     'guardian.backends.ObjectPermissionBackend',
# )

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],

    # Added for swagger
    # 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Pagination
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPaginationExtn',
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.PageNumberPaginationExtn',

    # Added for filtering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ]

}

# Simple JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "access-control-allow-origin",
    "access-control-allow-methods",
    "access-control-allow-credentials",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    # match localhost with any port
    # r"^http:\/\/localhost:*([0-9]+)?$",
    # r"^https:\/\/localhost:*([0-9]+)?$",

    # Match any hostname and any port
    r"^http:\/\/.*:*([0-9]+)?$",
    r"^https:\/\/.*:*([0-9]+)?$",
]

# DBBACKUP_DATABASES = ['default']
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.getenv('HOME', '.') + '/backup/Saturn/dbbackup'}
DBBACKUP_CLEANUP_KEEP = 30
DBBACKUP_CLEANUP_KEEP_MEDIA = 30
# DBBACKUP_HOSTNAME = os.getenv('HOSTNAME', 'localhost')

os.makedirs(os.getenv('HOME', ".") + '/backup/Saturn/dbbackup', exist_ok=True, )

CRONJOBS = [
    ('0 */6 * * *', 'server.db_backup_cronjob.backup')
]

JAZZMIN_SETTINGS = {
    "show_ui_builder": False,
    "site_logo": "Saturn_small.png",
    "login_logo": "Saturn.png",
}

# ATTACHMENT_DIR = "./attachments"
# os.makedirs(ATTACHMENT_DIR, exist_ok=True)
django_env_overrides.apply_to(globals())

